# This file was generated by GoReleaser. DO NOT EDIT.
cask "pomo" do
  version "1.2.1-cassette.1"

  on_macos do
    on_arm do
      sha256 "b994908ad876f06c8487b20fca62a18d51fb9b3743fc78c8b5263300987e245a"
      url "https://github.com/taotao7/pomo/releases/download/v#{version}/pomo_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "243b7f21de147657fc99973d92b129d6ca32d2a17bf232f37de3cadac809f3f1"
      url "https://github.com/taotao7/pomo/releases/download/v#{version}/pomo_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ae3b56b6a39f5e4a2b9063309d62658ff3036cda9dd9afbc67b40a4d4f7504ac"
      url "https://github.com/taotao7/pomo/releases/download/v#{version}/pomo_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "29fcbd4c83d0ae17dd5e14ea8b9e786784aba205c4c98ed140d79f26f6cc1d60"
      url "https://github.com/taotao7/pomo/releases/download/v#{version}/pomo_Linux_x86_64.tar.gz"
    end
  end

  name "pomo"
  desc "Pomodoro timer TUI with a Cassette Futurism progress bar"
  homepage "https://github.com/taotao7/pomo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pomo"

  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{staged_path}}/pomo"]
  end

  # No zap stanza required
end
